### ISSUE TITLE
apertium-apy doesn't honor -P / --log-path

### ISSUE THREAD

**Issue by kartikm** [apertium/apertium-apy#112]
New version of apertium-apy (>= 0.11.3) doesn't honor logging -P / --log-path= anymore

Test case:

mkdir /tmp/apy-log
/usr/bin/apertium-apy -j1 -m300 --daemon --log-path /tmp/apy-log -p 50000 /usr/share/apertium/modes

This prevents logging for service to files. Only stdout is shown.

**Comment by kartikm** [comment]
@TinoDidriksen Can you look into this?

**Comment by TinoDidriksen** [comment]
I don't Python much, and I am not knowledgeable of this codebase. So if it's critical: @sushain97 @unhammer 

A quick glance at the code looks correct (https://github.com/apertium/apertium-apy/blob/master/apertium_apy/apy.py#L248).

**Comment by unhammer** [comment]
Seems like @jonorthwash added the lines: https://github.com/apertium/apertium-apy/commit/cf48209eda132ccdf90db2b7cbf8c8501e6fb670 
I've never used `--daemon`, and still don't see the point, why not just `>apy.log 2>apy.err`?
(Also, why is an option named --daemon doing --redirect-output-to-log-path?)

**Comment by TinoDidriksen** [comment]
Redirection is not always an option, so passing filenames helps. But I guess this solves the mystery: `--log-path` is only applicable when `--daemon`

**Comment by jonorthwash** [comment]
I have no idea anymore what my thinking was when I added the logic for logging.  Please feel free to adjust as makes sense.

**Comment by sushain97** [comment]
Do we need a v0.11.4 release for this?

**Comment by kartikm** [comment]
Release with tarball would be nice!

**Comment by sushain97** [comment]
Release it out to PyPi. My apologies for the delay.
