### ISSUE TITLE
CSV/TSV source for lang names

### ISSUE THREAD

**Issue by sushain97** [apertium/apertium-apy#115]
Convert at build time

**Comment by jonorthwash** [comment]
I don't mind writing sql?

**Comment by sushain97** [comment]
But we're not the only one editing these :) I mentioned a couple more
reasons in IRC. (afk for a bit)

**Comment by sushain97** [comment]
Pros:
- Better rendering/look on GitHub/editor especially with TSV (subjective, I guess)
- Easier to edit, especially for non-SQL folks
- Easy to force sorting so that dupes are easy to see
- Smaller file size

Cons:
- Somewhat more complex build

**Comment by jonorthwash** [comment]
We also probably need to merge `turkic.sql` and `manual.sql`.

Another Pro:
- less confusing when input data is all tsv and output data is all sql.

We should keep a dichotomy between `scraped` and our modifications (whether we call it `manual` or something else).
