### ISSUE TITLE
Installation fails when building from source

### ISSUE THREAD

**Issue by ayushjainrksh** [apertium/apertium-apy#126]
Asynchronous attribute removed from tornado.web in the latest version causes installation of apertium-apy to fail when installing from source package using pip.

![whatsapp image 2019-03-06 at 2 11 14 am](https://user-images.githubusercontent.com/33171576/53839172-d74c1580-3fbc-11e9-915e-512ad5f5fc77.jpeg)

**Comment by sushain97** [comment]
Fixed in https://github.com/apertium/apertium-apy/commit/eb986aa7c7f93bdddbff554f187d8a1bbf7187a7.
