### ISSUE TITLE
Problem with apertium website translation

### ISSUE THREAD

**Issue by ayushjainrksh** [apertium/apertium-apy#145]
When translating apertium.org website from English to some language such as Spanish, the "Translate a webpage" button does not change. It changes in some cases. Any idea why this might be happening?

Translation from English to Spanish: 
![bug1](https://user-images.githubusercontent.com/33171576/75254912-1ba47700-5807-11ea-8616-21452f425cb0.png)

Translation from Spanish to Français: 
![bug2](https://user-images.githubusercontent.com/33171576/75254919-1e9f6780-5807-11ea-88d6-035959e1f78a.png)

Translation from Français to Spanish: 
![bug3](https://user-images.githubusercontent.com/33171576/75254925-219a5800-5807-11ea-9385-996efdece497.png)

**Comment by sushain97** [comment]
The interface leaves strings in whatever the last language you selected that has that string is. Not all strings are translated for all available languages.

**Comment by sushain97** [comment]
https://github.com/apertium/apertium-html-tools/blob/master/assets/strings/spa.json#L25 is missing.

This also has nothing to do with apy, it's all html-tools.
