### ISSUE TITLE
Fails to build with Tornado 6.x

### ISSUE THREAD

**Issue by kartikm** [apertium/apertium-apy#148]
Build of apertium-apy fails with: AttributeError: module 'tornado.web' has no attribute 'asynchronous'

See full log: https://salsa.debian.org/science-team/apertium-apy/-/jobs/744759

**Comment by sushain97** [comment]
This is due to pulling in Tornado 6.x which drops this decorator.

**Comment by kartikm** [comment]
Debian has tornado > 6 in unstable and soon it will be on stable release. Please fix build, so that Apertium can be run in Production systems (for example: ContentTranslation at Wikimedia runs on Debian, soon to be upgraded to latest Debian release.)
