### ISSUE TITLE
Translation pair spa-ast not working (always empty)

### ISSUE THREAD

**Issue by alrevuelta** [apertium/apertium-apy#157]
I'm trying to translate some text between `spa-ast` pairs, but I always get an empty response no matter the text I use.

First of all, these pairs are supported. In `https://beta.apertium.org/apy/listPairs` i can find:
```
...{"sourceLanguage": "spa", "targetLanguage": "ast"}...
```
But when I run the following query:
```
curl -G --data "langpair=spa|ast&q=hombre" https://beta.apertium.org/apy/translate
```
I get:
```json
{"responseData": {"translatedText": ""}, "responseDetails": null, "responseStatus": 200}
```

No matter which text I use, I always get a `translatedText:""`. I have tried using `spa-eng` (spanish/english) using the following command, and it works like a charm.

```
curl -G --data "langpair=spa|eng&q=hombre" https://beta.apertium.org/apy/translate
```

I get this response:
```json
{"responseData": {"translatedText": "Man"}, "responseDetails": null, "responseStatus": 200}(
```

So my questions are:
* Is there anything wrong with `ast` language? Or `spa-ast` pair perhaps?
* Is the apertium api linked in any way with the [online translator web](https://apertium.org/index.spa.html?dir=spa-ast&q=hombre#translation)? Is that link using this API under the hood? Can I assume that the results would be the same?

Thanks!
@pabloEntropia

**Comment by sushain97** [comment]
The APy instance at `apertium.org` works fine. The beta API you're hitting runs nightlies so maybe spa-ast is messed up at nightly?

**Comment by jonorthwash** [comment]
@TinoDidriksen, ↑

**Comment by TinoDidriksen** [comment]
Fixed by https://github.com/apertium/apertium-spa-ast/commit/949330b2af6541300e1d07dd39f017e069dd39c9

**Comment by alrevuelta** [comment]
Thank you all, now its working.
