### ISSUE TITLE
Languages appear as codes

### ISSUE THREAD

**Issue by ftyers** [apertium/apertium-apy#172]
I just got this in an email and I completely agree:
> Fa molt mal efecte que tant aquesta llengua com el savoi (arpità) no
> siguin anomenades, ans codificades. Sé pas què ho fa. - És com els
> formularis de certes xarxes, que a la casella d'idioma sols un
> grupuscle té el privilegi de ser anomenat pel nom. Totes les altres
> són entaforades dins el sac 'una altra llengua'; com si n'hi hagués
> cap que s'autoanomenés (autoqualifiques) de ser una altra llengua: una
> llengua diferent vista per si mateixa.

**Comment by jonorthwash** [comment]
Actually, looks like this is solved already?  Feel free to reopen if not.
![Screenshot from 2021-12-10 10-50-02](https://user-images.githubusercontent.com/963849/145602291-8a3ef13c-27a8-4218-9479-2ab7f543207a.png)
