### ISSUE TITLE
Local variable possibly mixed up with class' data attribute

### ISSUE THREAD

**Issue by ghost** [apertium/apertium-apy#19]
Local variable "serverlist" is possibly mixed up with class' data attribute on line 184 in gateway.py.

**Comment by unhammer** [comment]
gateway.py might need a complete rewrite; I don't know if it was ever completed (anyone tried it?)

**Comment by sushain97** [comment]
Hmm, I think the referenced line doesn't actually point to a `serverlist` anymore. However, I think the intended line is correct as written (just a bit confusing).

FWIW, no-one is running the gateway but it did work back I wrote it.
