### ISSUE TITLE
support unicode directly instead of using \u codes

### ISSUE THREAD

**Issue by jonorthwash** [apertium/apertium-apy#60]
Currently APy outputs unicode characters using \u codes, e.g. `'{"vblex": ["c\u00f3rrer"], "n": ["cursa"]}' chnages to '{"vblex": ["córrer"], "n": ["cursa"]}'`.

It would be more convenient if it output unicode directly, e.g. `'{"vblex": ["córrer"], "n": ["cursa"]}' chnages to '{"vblex": ["córrer"], "n": ["cursa"]}'`.

**Comment by sushain97** [comment]
How are you making the requests? This might be curl not properly decoding.

**Comment by jonorthwash** [comment]
@share-with-me ?

**Comment by TinoDidriksen** [comment]
It's APy outputting \u even when it doesn't need to. It's valid to output \u, but it's just not needed and makes the result harder to read. cURL does not and should not decode it.

We've looked at this before, but Tornado's escape module can't do it.

**Comment by jonorthwash** [comment]
It should be possible to override/extend Tornado's functions, though I'm not sure that this would be terribly future-proof?

**Comment by jonorthwash** [comment]
Either that, or we could file an issue with the Tornado folks.

**Comment by TinoDidriksen** [comment]
The Tornado folks have repeatedly denied requests for customizing escape.json (https://github.com/tornadoweb/tornado/issues/16, https://github.com/tornadoweb/tornado/issues/914, https://github.com/tornadoweb/tornado/issues/1202).

Their reply is to use another module, such as Python's own JSON encoder.

**Comment by jonorthwash** [comment]
Okay, then the solution is to reimplement how we encode json?  I assume that won't interfere with our ability to continue to use Tornado?

**Comment by share-with-me** [comment]
@jonorthwash , @sushain97 , apologies for the delayed reply.

> How are you making the requests? This might be curl not properly decoding.
> @share-with-me ?

I am using:

`curl -Ss "http://localhost:3025/dictionaryLookup?langpair=eng|cat&q=run"`

and the output is as follows:

`{"vblex": ["c\u00f3rrer"], "n": ["cursa"]}` on the CLI.

However, the AJAX call to fetch these values to the frontend parses the unicodes correctly and it gives

`'{"vblex": ["córrer"], "n": ["cursa"]}'`
