### ISSUE TITLE
.(null) when translating HTML-file

### ISSUE THREAD

**Issue by danielwalo** [apertium/apertium-apy#66]
When trying to translate [this file](https://github.com/goavki/apertium-apy/files/1309347/hn.zip) from Norsk Bokmål (nob) to Nynorsk (nno), I only get part of the file back. 

[The section I get back](https://github.com/goavki/apertium-apy/files/1309350/hn-back.zip) begins and ends with ".(null)"

Any way to pre-process the file to get around this?

Using https://www.apertium.org/apy/translateDoc?langpair=nob|nno&markUnknown=no

**Comment by Androbin** [comment]
Could it be the file contains some special character at that point?

**Comment by danielwalo** [comment]
Probably, but it’s not visible in Notepad, so I can’t tell.

**Comment by Androbin** [comment]
Can't reproduce when trying to translate from `en` to `es`.
(Of course nonsense, but this shows that it's not a parsing problem etc.)

**Comment by Androbin** [comment]
Can't reproduce with the following command:
`< hn.htm apertium -f html nob-nno > hh-back.htm`
Could you provide the exact command you used?

**Comment by danielwalo** [comment]
I was using apy.projectjj.com and www.apertium.org/apy

**Comment by SAP-20** [comment]
A newbie to open source.Sir,Can i work on the issue??

**Comment by TinoDidriksen** [comment]
This problem no longer occurs.
